### ISSUE TITLE
Can no longer build .aar using current build.gradle

### ISSUE THREAD

**Issue by robertesler** [libpd/pd-for-android#157]
With Android's new 16kb memory page size requirement coming on Nov. 1st, anyone using libpd will need to rebuild it for Android.  Currently, when I try to rebuild it I'm getting numerous errors.  The most current one that has me in a stand still is: 
`Execution failed for task ':PdCore:androidDependencies'.`
> Could not resolve all artifacts for configuration ':PdCore:debugCompileClasspath'.
   > Could not find com.noisepages.nettoyeur:midi:1.0.0-rc1.
     Required by:
         project :PdCore`

It's marked ` jcenter() // FIXME: com.noisepages.nettoyeur:midi`  in the project/build.gradle ln 37.  So what is the fix for this? 
Right now I'm using:
SDK 35
NDK 29.0.10433849
Build-tools 35.0.0

**Comment by Ant1r** [comment]
#152 should fix this, because it doesn't use `com.noisepages.nettoyeur:midi` anymore.

**Comment by robertesler** [comment]
@joebowbeer PR https://github.com/libpd/pd-for-android/pull/152 seems to fix the midi issue (compilation at least, I couldn't test MIDI on a device), and the 16kb memory pages issue (all .so libs are aligned for 16kb).  So that's great!

I just tried to build the @Ant1r dev2 fork, it doesn't actually assemble the .aar, at least not with `./gradlew clean assembleRelease`, maybe that will be fixed when it's merged with the main branch?  I could probably hand assemble it if needed for now.

There were also smaller, less important, errors in `opensl_stream.c`.  I had to add:
`#include <time.h>
#include <unistd.h>`
to get it to compile.  There were issues with `clock_gettime()` and `usleep()`.   I've had this issue before with other Android ndk  28+ builds.

And in PdService.java line 146 
`PdBase.setVerbose(verbose);` throws a 'cannot find symbol' error.  I checked and PdBase.java that is pulled does not have a `setVerbose()` method.  If you comment the line out, everything compiles.  This is probably because the git submodule is out of sync with the libpd main branch.   The current libpd branch has `PdBase.setVerbose()` but when you run `git submodule --init --recursive` it pulls an older commit.

@Ant1r and @joebowbeer thanks for the work you're doing on this issue.  Let me know if I can test or help with anything.

**Comment by robertesler** [comment]
@rpattabi, that's great you got it to build.  I'm still having the same problems.  Can you share your NDK version, SDK version, gradle version and/or Android Studio version, OS and any other relevant details?   I noticed this fork is still set for an older SDK and NDK.
